<a href="https://colab.research.google.com/github/cellrishi-code/ml----code/blob/main/nb_code_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import numpy as np
import pandas as pd

In [39]:
data = pd.read_csv('/content/play_tennis.csv')

In [40]:
data.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [41]:
data.drop(columns =['day'], inplace = True)

In [42]:
data.head()

    outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [43]:
# p(yes) and p(no)
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [44]:
py = 9/14
pn = 5/14

In [45]:
#for outlook column
pd.crosstab(data['outlook'], data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [46]:
pon = 0
psn = 2/5
prn = 3/5

poy =4/9
psy = 3/9
pry = 2/9

In [47]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [48]:
#for temp column
pd.crosstab(data['temp'], data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [49]:
phn = 1/5
pmn = 2/5
pcn = 2/5

phy = 3/9
pmy = 2/9
pcy = 4/9

In [50]:
#for humdity column
pd.crosstab(data['humidity'], data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [51]:
phighn = 4/5
pnormaln = 1/5

phighy = 3/9
pnormaly = 6/9

In [52]:
#for wind column
pd.crosstab(data['wind'], data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [53]:
pstrongn = 3/5
pweakn = 2/5

pstrongy = 3/9
pweaky = 6/9

In [54]:
# #prblm 1 ??
# outlook = sunny
# temp = hot
# humidity = high
# wind = weak

# p(yes|sunny,hot,high,weak) = p(sunny|yes).p(hot|yes).p(high|yes).p(weak|yes).p(yes)
# #

In [55]:
# p(yes|sunny,hot,high,weak) = p(sunny|yes).p(hot|yes).p(high|yes).p(weak|yes).p(yes)

In [56]:
pyes = psy * phy * phighy * pweaky * py
a =pyes          ## according to prblm 1 refered
print(a)

0.015873015873015872

In [57]:
pno = psn* phn * phighn * pweakn * pn
b = pno
print(b)

0.009142857142857145

In [58]:
if a> b :
  print('yes')
else :
  print('no')

yes

In [58]:
## this was the first prblm on navie bayes